### ISSUE TITLE
CRC algorithm

### ISSUE THREAD

**Issue by zabojad** [aesirot/ymodem#3]
Hi there !

I'm trying to implement YModem in my project but the CRC given by your lib doesn't seem to be right.

I've checked [this file pointed out by the YModem specifications](https://stuff.mit.edu/afs/sipb/user/paradis/zmodem/rbsb.c) and as I understand it, you do not implement the same updcrc() method.

Where do I misunderstand something :)?

Regards

**Comment by zabojad** [comment]
Forget it, I've found another implementation of CRC16 that works fine...

**Comment by aesirot** [comment]
Hi, zobojad.
You can look at class CRC16 and call it:
new CRC16().calcCRC(*your byte array*)

Are you sure you get wrong CRC ? 
I tested this algorithm and all was correct.

in my code:
((crc << 8) ^ table[((crc >> 8) ^ (0xff & b))]) & 0xFFFF;
in your reference:
crctab[((crc >> 8) & 255)] ^ (crc << 8) ^ cp

The difference is that I use xor to get value from table, while they don't and xor after.
Well... May be this is wrong.
Please give me a link to correct implementation, I will check and will post it in Wiki.

**Comment by zabojad** [comment]
Hey @aesirot !

Thank you for answering...

The implementation I've found and which works fine with my peripheral is [this one](http://www.ccsinfo.com/forum/viewtopic.php?t=24977).
